### ISSUE TITLE
Conside adding setup.json

### ISSUE THREAD

**Issue by ltalirz** [rubel75/aiida-wien2k#1]
Hi, while going through warnings thrown by the aiida registry, I noticed that you've been actively working on the plugin.

You may want to consider adding a `setup.json` to your repo and letting the plugin registry know about it so that it can extract information about the plugin (registered entry points, etc.). See https://github.com/aiidateam/aiida-diff/ for how this works

**Comment by sphuber** [comment]
Thanks @ltalirz . The package now contains a `pyproject.toml` which has been released on PyPI so I am closing this.
